services:
  - type: web
    name: qr-backend
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
    plan: free
