services:
  - type: web
<<<<<<< HEAD
    name: qr-code-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8080
=======
    name: qr-backend
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
    plan: free
>>>>>>> 2e9c449955cf6e1980ca90028781a485d88913bf
